Added device statuses and DeviceIsUp
ausocean/cloud pull request #127
Opened 2024-06-14 07:19 UTC by scruzin

2024-06-15 23:09 UTC, saxon-milton approved these changes

2024-06-15 23:09 UTC, saxon-milton commented on model/device.go
> +// the uptime is less than twice the monitor period,
Full stop

2024-06-15 23:26 UTC, saxon-milton requested changes

2024-06-15 23:26 UTC, saxon-milton commented on model/device.go
> -func (dev *Device) OutputListWithID() []string {
Ditto

2024-06-15 23:26 UTC, saxon-milton commented on model/device.go
> -func (dev *Device) InputListWithID() []string {
Was it intended that this be removed ?

2024-06-16 00:10 UTC, scruzin commented on model/device.go
> -func (dev *Device) InputListWithID() []string {
Yes. It's dead code.

2024-06-16 00:11 UTC, closed without merging