Bench: Prevent Changing of Youtube Channel (#155)
ausocean/cloud pull request #174
Opened 2024-06-28 03:57 UTC by ao-david

When the broadcast save action is called we will get the previously associated account for the broadcast and update the current config with that value to prevent users from changing this. The value can only be changed when the generate-token action is called. We will also not parse the value from the form to ensure this value can "never" be leaked through.

closes #155

2024-06-28 04:56 UTC, scruzin requested changes

2024-06-28 04:56 UTC, scruzin commented on cmd/oceanbench/broadcast.go
> +		cfg.Account = getExistingAccount(req.BroadcastVars, cfg)
Is getExistingAccount guaranteed to never fail?

2024-06-28 04:56 UTC, scruzin commented on cmd/oceanbench/broadcast.go
> +		return ""
Log upon failure.

2024-06-28 05:22 UTC, ao-david commented
I have just realised that this method is flawed. If the user changes the name of the broadcast, the broadcastFromVars function will be unable to find the old variable. We currently have no way of statefully finding the broadcast that has just been updated. It also looks like OceanTV will just lose track of an old config (broadcast variable) if the user changes the site name. This means that every time a user changes the name of a broadcast that a new variable is created as far as I can tell.

For now this means that we will just lose the value of the current YouTube channel when we change the name of a stream. Eventually this will be fixed when we associate the channel with the site rather than the broadcast.

2024-06-28 05:40 UTC, ao-david commented
> I have just realised that this method is flawed. If the user changes the name of the broadcast, the broadcastFromVars function will be unable to find the old variable. We currently have no way of statefully finding the broadcast that has just been updated. It also looks like OceanTV will just lose track of an old config (broadcast variable) if the user changes the site name. This means that every time a user changes the name of a broadcast that a new variable is created as far as I can tell.
> 
> For now this means that we will just lose the value of the current YouTube channel when we change the name of a stream. Eventually this will be fixed when we associate the channel with the site rather than the broadcast.

see #175

2024-06-29 00:40 UTC, saxon-milton approved these changes

2024-07-01 02:12 UTC, merged