Added installHander
ausocean/cloud pull request #221
Opened 2024-07-10 07:56 UTC by scruzin

This implements `installhandler`, which handles installation requests from new devices.

New devices are provisioned in a _sandbox_ site, and the operator is informed by email.
Once the operator has completed device configuration, the device will know its client type and will be able to complete its installation.

2024-07-16 23:16 UTC, saxon-milton requested changes

2024-07-16 23:16 UTC, saxon-milton commented on cmd/oceancenter/main.go
> +	case datastore.ErrNoSuchEntity:
I think this should use errors.Is

2024-07-16 23:16 UTC, saxon-milton commented on cmd/oceancenter/main.go
> +		var owner string
Consider simplifying this block to,
```
owner := sandboxOwner
if svc.standalone {
    owner = localEmail
}

```

2024-07-16 23:16 UTC, saxon-milton commented on cmd/oceancenter/main.go
> +	var (
no need for var block right ? Can do
```
wi := r.FormValue("wi")
/// etc....
```

2024-07-16 23:16 UTC, saxon-milton commented on cmd/oceancenter/main.go
> +	if err != datastore.ErrNoSuchEntity {
Prefer ```if !errors.Is(err,datastore.ErrNoSuchEntity)```

2024-07-16 23:16 UTC, saxon-milton commented on cmd/oceancenter/main.go
> +func checkTOTP(s string, digits int, secret []byte, period time.Duration) (bool, error) {
Is this a could candidate for writing a unit test ?

2024-07-17 12:30 UTC, trekhopton approved these changes
Minor comment but LGTM!

2024-07-17 12:30 UTC, trekhopton commented on cmd/oceancenter/main.go
> +	// GetCreate sandbox site its admin user if it doesn't exist.
*Get sandbox site and admin user, create them if they don't exist.

2024-07-18 03:15 UTC, merged