Ensure that utils form is not resubmitted (#288)
ausocean/cloud pull request #289
Opened 2024-08-13 04:23 UTC by ao-david

Previously, if the site was changed on the utils page, it would resubmit the form. Since moving a device puts a variable, then deletes it, if the user switches to the site the device was moved to, it will delete the variables associated with that device.

This change also update the error reporting in datablue which can hide the root issue.

closes #288

2024-08-13 05:13 UTC, scruzin approved these changes
LGTM but don't forget to bump the version too.

2024-08-13 05:15 UTC, scruzin requested changes
LGTM but don't forget to bump the version too.

Also, add a check to Ocean Bench `utilsHandler` to ensure `targetSkey != skey`. .

2024-08-20 05:13 UTC, trekhopton approved these changes

2024-08-21 07:40 UTC, scruzin approved these changes

2024-08-21 23:40 UTC, merged