AusOceanTV: Add Developer README
ausocean/cloud pull request #351
Opened 2024-11-11 05:40 UTC by ao-david

This readme should help developers with some of the project specific technologies used in the development of AusOcean TV.

Describes #350

2024-11-11 21:40 UTC, scott97 requested changes
One small change, otherwise it is good to go :+1:

2024-11-11 21:40 UTC, scott97 commented on cmd/ausoceantv/README.md
> +import style from './test.component.scss?inline'; // # See NOTE
From my testing this should be
```js
import style from './shared/tailwind.global.css?inline';
```

2024-11-11 21:46 UTC, scott97 approved these changes

2024-11-12 03:17 UTC, trekhopton commented
Cool that you can preview markdown in github using the view file option.

2024-11-12 03:26 UTC, trekhopton requested changes
Nice work. This will be helpful. Just a few typos.

2024-11-12 03:26 UTC, trekhopton commented on cmd/ausoceantv/README.md
> +AusOcean TV is a subscription service for accessing AusOceans premium streams.
*AusOcean's

2024-11-12 03:26 UTC, trekhopton commented on cmd/ausoceantv/README.md
> +To Allow for Tailwind styling to work with Lit components, AusOcean uses a
Allow -> allow

2024-11-12 05:05 UTC, ao-david commented
> Nice work. This will be helpful. Just a few typos.

Done: :relaxed:

2024-11-12 05:36 UTC, trekhopton approved these changes

2024-11-13 02:28 UTC, merged