AOTV: Create new subscriber on signin (#385)
ausocean/cloud pull request #388
Opened 2024-11-26 22:51 UTC by ao-david

When a new user signs in, check if there is an existing subscriber with the given email otherwise create a new subscriber.

closes #385

2024-11-28 03:51 UTC, trekhopton commented on cmd/ausoceantv/auth.go
> +	ID := model.NewSubscriberID(ctx, svc.settingsStore)
This will look different if ID is generated later by CreateSubscriber.

2024-11-28 03:51 UTC, trekhopton approved these changes

2024-11-30 21:31 UTC, saxon-milton requested changes

2024-11-30 21:31 UTC, saxon-milton commented on cmd/ausoceantv/auth.go
> +		return err
wrap error ?

2024-11-30 21:31 UTC, saxon-milton commented on cmd/ausoceantv/auth.go
> +	if errors.Is(err, SessionNotFound) || errors.Is(err, TokenNotFound) {
Would it be useful to have separate cases for these and then you can wrap the fiber error with more information i.e. whether it was a ```SessionNotFound``` or a ```TokenNotFound``` ?

Also, why exactly are we using the fiber error ?

2024-11-30 21:31 UTC, saxon-milton commented on cmd/ausoceantv/auth.go
>  func (svc *service) callbackHandler(c *fiber.Ctx) error {
I think the fiber context should be named like fCtx or something.

2024-11-30 21:31 UTC, saxon-milton commented on cmd/ausoceantv/auth.go
> +	ctx := context.Background()
So are there no ```context.Context``` in scope where ```callbackHandler``` is called that we could pass to this ?

2024-12-03 00:04 UTC, merged