bench: keep track of livestream visits with URL
ausocean/cloud pull request #402
Opened 2024-12-09 02:11 UTC by trekhopton

This was done because it should give us insights into how many people are visiting our streams through the URL redirect. The more user analytics the better.

I also remove saveLinkFunc and updateConfigWithTransaction from bench since they were unused duplicates.

2024-12-14 22:16 UTC, saxon-milton requested changes

2024-12-14 22:16 UTC, saxon-milton commented on model/variable.go
> +func PutVariableInTransaction(ctx context.Context, store datastore.Store, skey int64, name string, updateFunc func(currentValue string) string) error {
I think you can improve the structure of this and remove the store.Get

```
func PutVariableInTransaction(ctx context.Context, store datastore.Store, skey int64, name string, updateFunc func(currentValue string) string) error {
        // If a dot exists in the name, that indicates scope, remove any colons from the scope.
	sep := strings.Index(name, ".")
	scope := ""
	if sep >= 0 {
		scope = strings.ReplaceAll(name[:sep], ":", "")
		name = scope + name[sep:]
	}

	key := store.NameKey(typeVariable, strconv.FormatInt(skey, 10)+"."+name)

update:
	err = store.Update(ctx, key, func(entity datastore.Entity) {
		if v, ok := entity.(*Variable); ok {
			v.Value = updateFunc(v.Value)
			v.Updated = time.Now()
		}
	}, &variable)
        if errors.Is(err, ErrNoSuchEntity) {
              // The variable doesn't exist, initialize it with an empty value.
		variable = Variable{
			Skey:    skey,
			Name:    name,
			Scope:   scope,
			Value:   "",
			Updated: time.Now(),
		}

		// Create the variable in the datastore.
                err := store.Create(ctx, key, &variable)
                if errors.Is(err, ErrEntityAlreadyExists) {
                      // do nothing.
                }
                if err != nil {
                       return fmt.Errorf("failed to create variable: %w", createErr)
                }
                goto update
        }
	if err != nil {
		return fmt.Errorf("failed to update variable: %w", err)
	}

	if cache := variable.GetCache(); cache != nil {
		cache.Set(key, &variable)
	}

	return nil
```

2024-12-14 22:16 UTC, saxon-milton commented on cmd/oceanbench/broadcast.go
> +			if err != nil {
Maybe log ?

2024-12-23 02:31 UTC, trekhopton commented on cmd/oceanbench/broadcast.go
> +	go func() {
Because we can return quickly, which is preferable for a redirect handler, and update the count concurrently which may take longer.

2024-12-23 07:09 UTC, saxon-milton commented on cmd/oceanbench/broadcast.go
> +	go func() {
yeah fair enough

2025-01-22 03:14 UTC, trekhopton commented on model/variable.go
> +func PutVariableInTransaction(ctx context.Context, store datastore.Store, skey int64, name string, updateFunc func(currentValue string) string) error {
Good suggestion, done.

2025-01-28 04:26 UTC, ao-david approved these changes
LGTM. Has it been tested? And bump the version number

2025-01-28 04:26 UTC, ao-david commented on cmd/oceanbench/utils.go
> -func updateConfigWithTransaction(ctx context.Context, store Store, skey int64, broadcast string, update func(cfg *BroadcastConfig) error) error {
Is this supposed to be in this change?

2025-01-28 04:26 UTC, ao-david commented on cmd/oceanbench/broadcast.go
> -// writeHttpErrorAndLog is a wrapper for writeHttpError that adds logging.
Is this supposed to be in this change?

2025-01-28 20:29 UTC, saxon-milton commented on model/variable.go
> +// It is used to atomically update the variable's value in the datastore. The function should return both the updated value and any error
This is wrong now ?

2025-01-28 20:30 UTC, saxon-milton commented on model/variable.go
> +		if err != nil {
does this need to be else if ? Otherwise, datastore.ErrEntityExists will trigger this and not do nothing ?

2025-01-28 20:31 UTC, saxon-milton requested changes
Looks good once errors are corrected

2025-01-29 08:51 UTC, saxon-milton commented
Don't forget a minor version bump

2025-01-31 04:12 UTC, trekhopton commented on cmd/oceanbench/utils.go
> -func updateConfigWithTransaction(ctx context.Context, store Store, skey int64, broadcast string, update func(cfg *BroadcastConfig) error) error {
Yeah, if you read the PR description, I mention that I'm taking the opportunity to remove unused code. Hope you don't mind.

2025-01-31 04:12 UTC, trekhopton commented on cmd/oceanbench/broadcast.go
> -// writeHttpErrorAndLog is a wrapper for writeHttpError that adds logging.
Yeah removing unused code. See description of PR.

2025-01-31 04:12 UTC, trekhopton commented on model/variable.go
> +// It is used to atomically update the variable's value in the datastore. The function should return both the updated value and any error
Updated.

2025-01-31 04:12 UTC, trekhopton commented on model/variable.go
> +		if err != nil {
Yeah, good catch. Changed.

2025-01-31 04:16 UTC, merged