AOTV: Add priceID to checkout links from plans (#383)
ausocean/cloud pull request #413
Opened 2024-12-30 05:34 UTC by ao-david

This change adds a priceID query parameter to the links from the plans page to the checkout. This will allow for the checkout to determine which product is being purchased.

These priceIDs come from stripe, and will need to be updated if the products ever get changed. We could potentially think about making these be loaded via an API call to make sure they are always up to date, but I think this works for now.

2024-12-31 05:12 UTC, trekhopton approved these changes

2024-12-31 10:30 UTC, saxon-milton commented on cmd/ausoceantv/plans.html
> +      <plan-element plan-type="Day Pass" plan-cost="4" class="h-fit w-1/3" href="/checkout.html?priceID=price_1QZMqMDMhXzQAv2TK0EFunPO"></plan-element>
Maybe dumb question but could we have less obscure names for the priceIDs that then map them appropriately to the strip IDs ? Then you can have these IDs change (not sure why they would) and not have it break the frontend ?

2024-12-31 10:34 UTC, saxon-milton commented on cmd/ausoceantv/plans.html
> +      <plan-element plan-type="Day Pass" plan-cost="4" class="h-fit w-1/3" href="/checkout.html?priceID=price_1QZMqMDMhXzQAv2TK0EFunPO"></plan-element>
I think this would be following the “Thin Client, Thick Server” (or “Server-Driven UI”) principle more, if I'm actually understanding this.

2024-12-31 11:30 UTC, saxon-milton requested changes
Should we do a patch version bump ?

2025-01-01 22:22 UTC, ao-david commented on cmd/ausoceantv/plans.html
> +      <plan-element plan-type="Day Pass" plan-cost="4" class="h-fit w-1/3" href="/checkout.html?priceID=price_1QZMqMDMhXzQAv2TK0EFunPO"></plan-element>
I don't know that changing that would make the system any better, I think it would actually make the system more complex with no benefit. Either way, when the priceIDs change, they have to be updated somewhere, leaving them here is the least amount of code, and I would argue possibly easiest to update.

I think at some stage this setup will be changed to dynamically controlled by a request to a stripe API to get the up to date products, and their pricing.

BTW, the priceIDs shouldn't change unless we change the product (or accidentally delete, which I have already done once...)

2025-01-01 22:33 UTC, saxon-milton commented on cmd/ausoceantv/plans.html
> +      <plan-element plan-type="Day Pass" plan-cost="4" class="h-fit w-1/3" href="/checkout.html?priceID=price_1QZMqMDMhXzQAv2TK0EFunPO"></plan-element>
I'm not sure I really agree; having stripe price IDs hardcoded into the HTML does not sound like a good design decision IMO, and less code is certainly not always better.

This doesn't have to change now, but I think some of the other ideas on how this should work are better.

2025-01-01 23:48 UTC, ao-david commented on cmd/ausoceantv/plans.html
> +      <plan-element plan-type="Day Pass" plan-cost="4" class="h-fit w-1/3" href="/checkout.html?priceID=price_1QZMqMDMhXzQAv2TK0EFunPO"></plan-element>
Yeah ok, I think there may be bigger fish to fry at the moment, but will make an issue to improve later. See #419

2025-01-02 00:28 UTC, saxon-milton approved these changes

2025-01-03 05:47 UTC, merged