AOTV: Support Stripe Subscriptions (#383)
ausocean/cloud pull request #414
Opened 2024-12-30 05:35 UTC by ao-david

This change adds proper support for stripe subscriptions, as well as keeping support for once off purchases.

Requires #413

2024-12-31 05:24 UTC, trekhopton approved these changes
Minor comments.

2024-12-31 05:24 UTC, trekhopton commented on cmd/ausoceantv/stripe.go
> +		return fmt.Errorf("error getting price: %v", err)
%w

2024-12-31 05:24 UTC, trekhopton commented on cmd/ausoceantv/stripe.go
>  		log.Errorf("Error creating new Stripe payment intent: %v", err)
Error -> error

No need for capitalisation.

2024-12-31 11:06 UTC, saxon-milton requested changes

2024-12-31 11:06 UTC, saxon-milton commented on cmd/ausoceantv/stripe.go
> +		log.Errorf("subscription.New: %v", err)
Is this log redundant if we're just going to log the return error below on the level above ?

2024-12-31 11:30 UTC, saxon-milton requested changes
Should do minor ver bump ?

2025-01-01 22:29 UTC, ao-david commented on cmd/ausoceantv/stripe.go
> +	// Check for an existing payment intent that is not complete.
This could happen if a user starts checking out and then returns to the plans page, then selects a plan again and starts checking out again. Stripe recommends reusing the intent as it allows you to track changes to the cart etc over time. This could also happen if payment failed etc...

2025-01-02 00:21 UTC, ao-david commented on cmd/ausoceantv/stripe.go
> +			log.Errorf("error updating payment intent, will retry with new payment intent: %v", err)
I want it to fallthrough so that it just creates a new payment intent instead.

2025-01-02 00:23 UTC, saxon-milton commented on cmd/ausoceantv/stripe.go
> +			log.Errorf("error updating payment intent, will retry with new payment intent: %v", err)
Sorry, I see

2025-01-02 00:28 UTC, saxon-milton approved these changes

2025-01-03 05:49 UTC, merged