AOTV: Add cart info to checkout page.
ausocean/cloud pull request #415
Opened 2024-12-30 05:38 UTC by ao-david

This change adds the current cart to the checkout page such that the user can see what they are purchasing.
![image](https://github.com/user-attachments/assets/50c404bf-1731-4fcd-a0b1-a8d698efca27)

requires #414 
closes #383

2024-12-31 05:39 UTC, trekhopton approved these changes

2024-12-31 11:11 UTC, saxon-milton requested changes

2024-12-31 11:11 UTC, saxon-milton commented on cmd/ausoceantv/src/checkout.js
> +  // Extract the 'priceID' query parameter from the URL
dumb question, but can we do all this on the backend ?

2024-12-31 11:11 UTC, saxon-milton commented on cmd/ausoceantv/src/checkout.js
> +  // Update the values.
DN

2024-12-31 11:11 UTC, saxon-milton commented on cmd/ausoceantv/stripe.go
> +		return fmt.Errorf("must specify price_id")
```errors.New```

2024-12-31 11:11 UTC, saxon-milton commented on cmd/ausoceantv/stripe.go
> +		return fmt.Errorf("must specify price_id")
Also, I think this should be "price_id empty"

2024-12-31 11:11 UTC, saxon-milton commented on cmd/ausoceantv/stripe.go
> +		return fmt.Errorf("must specify product_id")
```errors.New```

2024-12-31 11:30 UTC, saxon-milton reviewed
Minor or patch bump ?

2025-01-01 22:33 UTC, ao-david commented on cmd/ausoceantv/src/checkout.js
> +  // Extract the 'priceID' query parameter from the URL
Which bit?

2025-01-01 22:56 UTC, saxon-milton commented on cmd/ausoceantv/src/checkout.js
> +  // Extract the 'priceID' query parameter from the URL
Looking at this more, I guess don't understand why we wouldn't just get the priceID on the backend and make the required requests there (just trying to minimise javascript) ? I'm assuming the reason is because this is faster i.e. page loads and then stuff is populated on the page ?

2025-01-01 23:16 UTC, ao-david commented on cmd/ausoceantv/src/checkout.js
> +  // Extract the 'priceID' query parameter from the URL
I'm not sure if you are aware, but we aren't using server side rendering on AusOceanTV so any dynamic content has to be loaded via js from the frontend (at least in my understanding). @trekhopton or @scott97 may be able to chime in here.

2025-01-01 23:37 UTC, saxon-milton commented on cmd/ausoceantv/src/checkout.js
> +  // Extract the 'priceID' query parameter from the URL
hhmm maybe we'll take this offline.

2025-01-10 00:50 UTC, merged