AOTV: Update to new Gauth implementation
ausocean/cloud pull request #417
Opened 2024-12-31 03:08 UTC by ao-david

This change updates AusOceanTV to run on the new implementation of Gauth which uses the backend package.

2024-12-31 11:21 UTC, saxon-milton requested changes

2024-12-31 11:21 UTC, saxon-milton commented on cmd/ausoceantv/main.go
> +		log.Fatalf("unable to get sessionKey secret: %v", err)
This seems more like a programmer error (?) in which case we should use panic (?). We can also recover panics (plus do fancy things like email notify), and it show a stacktrace. ```log.Fatalf``` on the other hand uses ```os.Exit(1)``` which is pretty harsh.

2024-12-31 11:31 UTC, saxon-milton reviewed
Patch ver bump ?

2025-01-01 22:25 UTC, ao-david commented on cmd/ausoceantv/main.go
> +		log.Fatalf("unable to get sessionKey secret: %v", err)
I'm not sure if there is a downside to using panic, I was using fatal because this step is really part of the setup, and the setup function says that ```Any errors are considered fatal```

2025-01-01 23:22 UTC, ao-david commented
> Patch ver bump ?

Done

2025-01-03 05:40 UTC, merged