AOTV: Add endpoints for subscriptions
ausocean/cloud pull request #418
Opened 2024-12-31 03:15 UTC by ao-david

This change adds 2 new endpoints, ```/get/subscription``` and ```/stripe/cancel```. These will allow the front-end to get data about the subscription and cancel the subscription respectively.

2024-12-31 06:25 UTC, trekhopton approved these changes

2024-12-31 11:27 UTC, saxon-milton requested changes

2024-12-31 11:27 UTC, saxon-milton commented on cmd/ausoceantv/main.go
> +	version       = "v0.1.7"
This change is more like a minor bump.

2024-12-31 11:27 UTC, saxon-milton commented on cmd/ausoceantv/main.go
> +	if err != nil {
Do all ```err != nil``` correspond to an ```api.Unauthorized``` error ?

2024-12-31 11:27 UTC, saxon-milton commented on cmd/ausoceantv/main.go
> +	subscription, err := model.GetSubscription(ctx, svc.settingsStore, subscriber.ID, 0)
0 is magic number ?

2024-12-31 11:27 UTC, saxon-milton commented on cmd/ausoceantv/main.go
> +	// Check that the subscription is still valid.
Maybe elaborate on this one.

2024-12-31 11:27 UTC, saxon-milton commented on cmd/ausoceantv/main.go
> +	c.JSON(subscription)
Should this be ```return c.JSON(subscription)``` ?

2024-12-31 11:27 UTC, saxon-milton commented on cmd/ausoceantv/stripe.go
> +	if err != nil {
ditto

2024-12-31 11:27 UTC, saxon-milton commented on cmd/ausoceantv/stripe.go
> +	// TODO: Update the Stripe subscription to cancel at period end.
Should this be louder ? Should we check for period end and call ```panic("unimplemented")``` ?

2025-01-01 23:29 UTC, ao-david commented on cmd/ausoceantv/stripe.go
> +	// TODO: Update the Stripe subscription to cancel at period end.
I agree that this should probably be louder, although I'm not sure my comment was very clear.

What I am saying here is that what I have done so far doesn't actually cancel the subscription on stripe and so the user will still get charged. Currently it only cancels it in our records. I am going to work on this immediately, but will also make it panic here?

2025-01-01 23:36 UTC, saxon-milton commented on cmd/ausoceantv/stripe.go
> +	// TODO: Update the Stripe subscription to cancel at period end.
It all depends on how quickly we can get to it. If it was something very important that we weren't going to work on immediately then a ```panic("unimplemented")``` is a good idea, but if you're going to work on it pretty soon then probably DN.

2025-01-03 05:45 UTC, merged